-- CreateTable
CREATE TABLE "public"."sarh_funcionario" (
    "COD_FUNCIONARIO" INTEGER NOT NULL,
    "CPF" VARCHAR(4000) NOT NULL,
    "NOME" VARCHAR(50),
    "MATRICULA" VARCHAR(15),
    "E_MAIL" VARCHAR(60),
    "ENDERECO" VARCHAR(100),
    "BAIRRO" VARCHAR(50),
    "CIDADE" VARCHAR(50),
    "TELEFONE" VARCHAR(20),
    "ID_TIPO_LOTACAO" INTEGER,
    "LOTACAO" VARCHAR(120),
    "SIGLA" VARCHAR(20),
    "CARGO" VARCHAR(100),

    CONSTRAINT "sarh_funcionario_pkey" PRIMARY KEY ("COD_FUNCIONARIO")
);
